### ISSUE TITLE
First Major Sprint 

### ISSUE THREAD

**Issue by unibitlabs** [UniBitProject/wallet#1]
Milestones for the sprint

**Comment by infopirate** [comment]
@gitcoinbot help

**Comment by unibitlabs** [comment]
Current situation:
Wallet is in BETA development only mode.

You currently need to modify the config.json to your blockchains parameters before running the wallet.

This information is stored in a file located at and called -
/home/user/.multichain/chainname.config

It will look like this -
picture of chain params file from a new chain generated.

Once you have your chains parameters, you will open the config.json file in a text editor and replace the info in it with the new chain parameters.

Save & Close. X2 due to the files being duplicated!! * Bug #2 
* File config.json is in 2 places... the root dir, and the /app dir. Change & Save Both until we remove the unnecessary one. 

Then you are ready to run the usual..
npm install && npm start

on macOS:
npm install && npm start-mac

you should see this -
picture of wallet running

then once you press the connect button -
pic of wallet with chain params showing..

This is currently all that is happening. 


End Goal:

Fix This issue, fix bug #2, keep issues. bounties, all flowing to the discord dev channel...

**Comment by unibitlabs** [comment]
goal #1 - button to generate blockchain and grab/copy/paste params into config.json by default after generation.

goal #2 - button to connect to existing blockchain with inputted parameters. 

goal #3 - fix mac error about addresses.txt 

these 3 goals are a very successful sprint.
